version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3  # Persist the SQLite database file
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-2hmocd!^6+csg63kwsb4o%^qxacsxs#rbj@$_iyo9$3m-2tgog
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
